>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: new connection on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
parsing new chunck of size: 541
URI = /hello_form.py?fname=fiz&lname=portela
URI_FILE = hello_form.py
QUERY STRING = fname=fiz&lname=portela
str = .py
searching for location with path: >/<
cgis = .out
cgis = .cgi
cgis = .py
isCGI = 1
Method: GET, uri: /hello_form.py?fname=fiz&lname=portela, protocol: HTTP/1.1
Head:
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.5
Connection:keep-alive
Host:localhost:8082
Referer:http://localhost:8082/formulario_get_python.html
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:same-origin
Sec-Fetch-User:?1
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
Body:


server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

<<<<<<<<<READY TO ANSWER>>>>>>>>>
searching for location with path: >/<
IT SHOULD NEVER GET HERE
going to send(7, (str + 0), 177, 0
sent succesfully
server: response sent on socket 7

Client 7 reset (keeping alive)
<<<<<<<<<ANSWERED, CLOSED OR RESETED>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
searching for location with path: >/<
IT SHOULD NEVER GET HERE
going to send(7, (str + 0), 63, 0
sent succesfully
server: response sent on socket 7

Client 7 reset (keeping alive)
<<<<<<<<<ANSWERED, CLOSED OR RESETED>>>>>>>>>

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: client 7 closed connection
closing client7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: new connection on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
<<<<<<<<<NOT READY TO ANSWER>>>>>>>>>

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
parsing new chunck of size: 505
URI = /formulario_post_python.html
URI_FILE = formulario_post_python.html
QUERY STRING = 
str = .html
searching for location with path: >/<
cgis = .out
cgis = .cgi
cgis = .py
cgis = .php
isCGI = 0
Method: GET, uri: /formulario_post_python.html, protocol: HTTP/1.1
Head:
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.5
Connection:keep-alive
Host:localhost:8082
Referer:http://localhost:8082/
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:same-origin
Sec-Fetch-User:?1
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
Body:


server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

<<<<<<<<<READY TO ANSWER>>>>>>>>>
searching for location with path: >/<
going to send(7, (str + 0), 429, 0
sent succesfully
server: response sent on socket 7

Client 7 reset (keeping alive)
<<<<<<<<<ANSWERED, CLOSED OR RESETED>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
searching for location with path: >/<
  -trying index: >/Users/test/Desktop/wardit/webserv/www/8082/index.html<
going to send(7, (str + 0), 697, 0
sent succesfully
server: response sent on socket 7

Client 7 reset (keeping alive)
<<<<<<<<<ANSWERED, CLOSED OR RESETED>>>>>>>>>

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: client 7 closed connection
closing client7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: new connection on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
parsing new chunck of size: 642
URI = /hello_form.py
URI_FILE = hello_form.py
QUERY STRING = 
aux + bodylen >= content_length
str = .py
searching for location with path: >/<
cgis = .out
cgis = .cgi
cgis = .py
isCGI = 1
Method: POST, uri: /hello_form.py, protocol: HTTP/1.1
Head:
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.5
Connection:keep-alive
Content-Length:23
Content-Type:application/x-www-form-urlencoded
Host:localhost:8082
Origin:http://localhost:8082
Referer:http://localhost:8082/formulario_post_python.html
Sec-Fetch-Dest:document
Sec-Fetch-Mode:navigate
Sec-Fetch-Site:same-origin
Sec-Fetch-User:?1
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
content-type:
Body:
fname=fiz&lname=portela

server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

<<<<<<<<<READY TO ANSWER>>>>>>>>>
searching for location with path: >/<
========================================
going to send(7, (str + 0), 178, 0
sent succesfully
server: response sent on socket 7

Client 7 reset (keeping alive)
<<<<<<<<<ANSWERED, CLOSED OR RESETED>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
searching for location with path: >/<
========================================
going to send(7, (str + 0), 63, 0
sent succesfully
server: response sent on socket 7

Client 7 reset (keeping alive)
<<<<<<<<<ANSWERED, CLOSED OR RESETED>>>>>>>>>

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: client 7 closed connection
closing client7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

