>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: new connection on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
aux + bodylen >= content_length
body size = 245517
server: message read and parsed on socket 7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

<<<<<<<<<READY TO ANSWER>>>>>>>>>
========================================
server: response sent on socket 7

Client 7 reset (keeping alive)
<<<<<<<<<ANSWERED, CLOSED OR RESETED>>>>>>>>>

<<<<<<<<<READY TO ANSWER>>>>>>>>>
========================================
server: response sent on socket 7

Client 7 reset (keeping alive)
<<<<<<<<<ANSWERED, CLOSED OR RESETED>>>>>>>>>

>>>>>>>>>INCOMING CONNECTION<<<<<<<<<
server: client 7 closed connection
closing client7
>>>>>>>>>INCOMING CONNECTION PROCESSED<<<<<<<<<

